name: Multiple deployu to GH Pages
description: deploy with running some scripts meanwhile
author: Jakub Hajduk <jakub.hajduk@xebia.com>
branding:
  color: 'purple'

runs:
  using: 'composite'

  steps:
    - run: echo hello
      shell: bash

inputs:
  commands:
    description: Commands to run after fetching gh-pages branch
    required: true
    default: echo 'No commands!'

  temp-dir:
    description: name of the temporary directory
    required: true
    default: 'ghp-temp'

  deploy-branch:
    description: "Branch to deploy. (defalut: gh-pages)"
    required: true
    default: 'gh-pages'
