name: Component preview

on:
  pull_request:
    types: [openned, synchronize, reopenned]

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    env:
      PREVIEW_DIRNAME: ''

    steps:
      - name: Dump github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Update preview dirname
        run: echo "PREVIEW_DIRNAME=$(echo '${{ github.head_ref }}' | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install and build docs
        run: |
          npm ci
          npm run build:preview

      - name: Deploy
        uses: ./.github/actions/pages-deploy
        with:
          temp-dir: ghp-temp
          commands: |
            mkdir -p ghp-temp/preview/${{ env.PREVIEW_DIRNAME }}
            cp -r preview/. ghp-temp/preview/${{ env.PREVIEW_DIRNAME }}
            tree

      - name: Add comment with link
        uses: ./.github/actions/comment
        with:
          prefix: ":sparkles: :sparkles: :sparkles:"
          body: |
            [New preview link](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/preview/${{ env.PREVIEW_DIRNAME }}/index.html) for this branch has been created.
            :sparkles: Other thing
