name: Component preview

on:
  pull_request:
    types: [openned, synchronize, reopenned]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    env:
      PREVIEW_DIRNAME: ''

    steps:
      - name: Dump github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Update preview dirname
        run: echo "PREVIEW_DIRNAME=$(echo '${{ github.head_ref }}' | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install and build docs
        run: |
          npm ci
          npm run build:preview

      - name: Deploy
        uses: ./.github/actions/pages-deploy
        with:
          temp-dir: ghp-temp
          commands: |
            mkdir -p ghp-temp/preview/${{ env.PREVIEW_DIRNAME }}
            cp -r preview/. ghp-temp/preview/${{ env.PREVIEW_DIRNAME }}
            tree

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.number }}
          body-includes: ":sparkles: New preview link for this branch has been created."

      - name: Create comment with link
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: ":sparkles: [New preview link](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/preview/${{ env.PREVIEW_DIRNAME }}/index.html) for this branch has been created."
