name: Component preview

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Dump github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and build docs
        run: |
          npm ci
          npm run build:preview

      - name: Deploy
        uses: ./.github/actions/pages-deploy
        with:
          temp-dir: ${{ env.GHP_TEMP_PATH }}
          commands: |
            cp -r preview/. ghp-temp/${{ github.ref_name.replaceAll('/', '-') }}

