name: Component preview

on:
  pull_request:
    types: [openned, synchronize, reopenned]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install and build docs
        run: |
          npm ci
          npm run build:preview

      - name: Deploy
        uses: ./.github/actions/pages-deploy
        with:
          temp-dir: ghp-temp
          commands: | 
            mkdir -p ghp-temp/preview/$(node -e "console.log('${{ github.head_ref }}'.replaceAll('/', '-'))")
            cp -r preview/. ghp-temp/preview/$(node -e "console.log('${{ github.head_ref }}'.replaceAll('/', '-'))")
            tree
