name: package.json info
description: Fetch data from package.json file
author: Jakub Hajduk <jakub.hajduk@xebia.com>
branding:
  color: 'purple'

runs:
  using: 'composite'

  steps:
    - name: Get data
      run: echo contents=$(cat package.json) >> $GITHUB_OUTPUT
      shell: bash

outputs:
  contents: ''
