name: Pkg
description: Fetch data from package.json file
author: Jakub Hajduk <jakub.hajduk@xebia.com>
branding:
  color: 'purple'

runs:
  using: 'composite'

  steps:
    - name: Get data
      id: pkg
      run: echo contents=$(cat package.json) >> $GITHUB_OUTPUT
      shell: bash

outputs:
  contents:
    description: "package.json contents"
    value: ${{ steps.pkg.outputs.contents }}
